name: RoleplayFeatures
version: ${project.version}
main: ml.zdoctor.RoleplayFeatures
authors: [ zDoctor_ ]
description: Add some features that a roleplay needs
website: zdoctor.ml
softdepend:
  - PlaceholderAPI